baseurl = "https://mailsquad.com/en"
publishdir = "../../html/en"
staticdir = "../static"
canonifyurls = false

title = "Email marketing solution for agencies"

[[menu.top]]
	name = "Pricing"
	identifier = "pricing"
	url = "/pricing"
	weight = 2
[[menu.top]]
	name = "Contact"
	identifier = "contact"
	url = "/contact"
	weight = 3
[[menu.top]]
	name = "Support"
	identifier = "support"
	url = "http://help.mailsquad.com"
	weight = 4